version: '3'
networks:
  laravel:
services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: form_kurang_nginx
    ports:
      - 80:80 #sesuaikan
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: form_kurang_php
    volumes:
      - ./src:/var/www/html:delegated
    user: root
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: form_kurang_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: root
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html:delegated
    working_dir: /var/www/html
    user: root
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel